### ISSUE TITLE
Bug in persistState.js

### ISSUE THREAD

**Issue by Graf009** [elgerlambert/redux-localstorage#10]
The code persistState.js https://github.com/elgerlambert/redux-localstorage/blob/1.0-breaking-changes/src/persistState.js#L40 uses a variable "finalReducer", but I think that there should "reducer"

**Comment by elgerlambert** [comment]
I was afraid something like this would happen. I'm away for the next three weeks.. could you do me a favour and create a PR to fix this bug? Can't fix it myself, but I'll be able to accept a PR.

My apologies!

**Comment by 0x80** [comment]
I'm trying to install the module including this patch with `npm install elgerlambert/redux-localstorage#4b2e1a8`, but the resulting module folder only contains a README and a package.json. Is that not the correct way to install an npm module from a specific commit?

**Comment by chrishoage** [comment]
@0x80 This npm module is written in ES6, so it requires a compile step. In the `.npmignore` file it contains `src` which causes npm to remove that folder when installing though git making the compile step impossible. 

The only way to use the RC currently is to check out the project separate from npm, run `npm prepublish` and then `npm link` until @elgerlambert can release a new RC with the fix.

**Comment by 0x80** [comment]
Thanks @chrishoage that makes total sense!

**Comment by elgerlambert** [comment]
Hi guys, the fix for this issue has just been published to npm as rc4. Apologies for the delay (currently traveling with infrequent access to wifi and I only have a tablet with me).
