### ISSUE TITLE
Code should not touch DOM if it's not called

### ISSUE THREAD

**Issue by steida** [elgerlambert/redux-localstorage#19]
https://github.com/elgerlambert/redux-localstorage/blob/1.0-breaking-changes/src/persistState.js#L6

This makes lib unusable in server.

**Comment by elgerlambert** [comment]
Hi @steida, thanks for reporting the issue.

Some discussion has already taken place in relation to this issue. I'd like to refer to you to #13 incase you have something you'd like to add to the discussion. I'll be setting some time aside this week to resolve this and other issues.

**Comment by steida** [comment]
I switched to https://github.com/michaelcontento/redux-storage, seems to have better api and functionality.
