### ISSUE TITLE
Passing in a string array as paths returns error

### ISSUE THREAD

**Issue by anthonator** [elgerlambert/redux-localstorage#20]
I'm getting this error when I try to initialize `persistState`.

```
Uncaught TypeError: finalStorage.get is not a function
```

If I pass in a string or void I don't get any issues.

```js
const store = compose(
  middleware,
  persistState(['jwt']),
  reduxReactRouter({ getRoutes, createHistory })
)(createStore)(reducers);
```

**Comment by vicentedealencar** [comment]
What version of redux-localstorage are you using?

Check out branch [1.0-breaking-changes](https://github.com/elgerlambert/redux-localstorage/tree/1.0-breaking-changes)

**Comment by anthonator** [comment]
1.0.0-rc4

**Comment by elgerlambert** [comment]
Hi @anthonator, the Readme on master shows the docs associated with `0.4.0`. Be sure to check out the [Readme associated with the 1.0-breaking-changes branch](https://github.com/elgerlambert/redux-localstorage/tree/1.0-breaking-changes), since you're using `1.0.0-rc4`.

**Comment by anthonator** [comment]
Got it. Thanks!
