### ISSUE TITLE
persistStateMiddleware returns action

### ISSUE THREAD

**Issue by 4ega** [elgerlambert/redux-localstorage#27]
Hi I have an issue in my app with persistStateMiddleware. 

https://github.com/elgerlambert/redux-localstorage/blob/1.0-breaking-changes/src/persistStateMiddleware.js#L10-L18

I have some logic based on value that is returned from my middleware chain, but persistStateMiddleware brakes it because it returns action, instead of `return next(action);`. Is there a reason of returning `action`? Maybe persistStateMiddleware can return result of next instead of action?

**Comment by elgerlambert** [comment]
Hi @4ega,

This has been fixed by #34 (and is available on npm)
