### ISSUE TITLE
What is the recommended way to persist Immutable js state with the new API?

### ISSUE THREAD

**Issue by kiranp11** [elgerlambert/redux-localstorage#28]
Hello,

I'm using the  "redux-localstorage": "^1.0.0-rc4". What is the recommended way to handle serialisation/deserialization of a Immutable js state with the new API?

Is there any thing similar to config, that gave an handle to achieve this in the older API?

Thanks in advance

Kiran.

**Comment by jakelazaroff** [comment]
I wrote an enhancer that allows you to do this! https://www.npmjs.com/package/redux-localstorage-immutable

Let me know how it works :grin:

**Comment by elgerlambert** [comment]
Hi @kiranp11,

A storage enhancer would definitely be the way to go about this. Looks like @jakelazaroff already took care of this! I also saw you already added it to the wiki, much appreciated! Thanks!
