### ISSUE TITLE
I would love to take advantage of this, but I need to be able to ignore certain actions. 

### ISSUE THREAD

**Issue by ericwooley** [elgerlambert/redux-localstorage#37]
I am using redux router, and there is a change action on every input change, which chugs with this module. 

would it be difficult to add a config for action types that should not trigger a change, a la `redux-form/CHANGE`

I don't have a ton of time, but if you think this would be an easy PR, I could probably look into doing it.

**Comment by ericwooley** [comment]
After looking more into how redux local storage works, I don't see it being possible to ignore actions.

@elgerlambert How would you feel about adding a debounce option?

**Comment by BartWaardenburg** [comment]
Sound like this little plugin by @elgerlambert is exactly what you want: https://github.com/elgerlambert/redux-localstorage-debounce

**Comment by ericwooley** [comment]
@BartWaardenburg Wow, thats too easy. 

Thanks!
