### ISSUE TITLE
Having trouble setting up store for redux-localstorage.

### ISSUE THREAD

**Issue by jamesone** [elgerlambert/redux-localstorage#38]
I'm trying to have a seperate store for only my `user` object so I can store authentication keys & user information. But there is a lack of examples on here!  

The examples on this repo seem to cater for apps that store all it's data locally? Is there a way I can only setup the redux-localstorage to work with a single reducer (user)?

Stack question that I posted below:
http://stackoverflow.com/questions/36260196/having-trouble-setting-up-redux-localstorage-to-work-with-existing-store

**Comment by vicentedealencar** [comment]
I answered on SO, hope it helps

**Comment by elgerlambert** [comment]
Hi @jamesone,

Your question on SO and here seem to concern different issues.. did you manage to resolve them?

To answer your question above, if you only want to persist part of your store I invite you to have a look at [redux-localstorage-filter](https://github.com/elgerlambert/redux-localstorage-filter) which is a storage enhancer intended to help do just that.

**Comment by elgerlambert** [comment]
Closing this for now, but definitely let me know if you still need help!
