### ISSUE TITLE
Need a fallback when localStorage is not available

### ISSUE THREAD

**Issue by bhoomit** [elgerlambert/redux-localstorage#47]
There are two cases where I'm having trouble.

1. Safari private browser
2. Server side rendering 

In both the cases local-storage is not available and it stops executing further. 

How should I fix this issue?

**Comment by jden** [comment]
you can stub it in your code with something like
```js
import adapter from 'redux-localstorage/lib/adapters/localStorage'

const localStore = window.localStorage || {}

adapter(window.localStorage)

...
```

**Comment by elgerlambert** [comment]
Hi @bhoomit,

Should be fixed now! (1.0.0-rc5)

**Comment by bhoomit** [comment]
@elgerlambert thanks :) Will check.

**Comment by alicewriteswrongs** [comment]
I'm using 1.0.0-rc5 and seeing exceptions when `localStorage` is not available, is the solution above still necessary (doing some sort of stub) to handle those cases?

**Comment by alicewriteswrongs** [comment]
disregard my comment! ✌
