### ISSUE TITLE
Add maintainer or community maintenance fork

### ISSUE THREAD

**Issue by jden** [elgerlambert/redux-localstorage#48]
has anyone heard from @elgerlambert lately? Quite a few people are using redux-localstorage, based on the npm download count. There are also a good number of open issues and PRs, and an ongoing pre-v1.0.0 branch and release series on npm. The last release, 1.0.0-rc4, was 2015-09-11, quite some time ago.

It would be great to be able to continue development in this repo and in this npm package namespace.

There's already a community maintenance fork at https://www.npmjs.com/package/redux-localstorage-fix-localstorage-fork . If this repo is no longer going to be maintained, we should think about transitioning to a single fork that can accept PRs.

**Comment by jden** [comment]
Related: #32

**Comment by elgerlambert** [comment]
Hi @jden,

Really sorry about dropping the ball on this one. I intent to do a better job going forward!

**Comment by Sigfried** [comment]
Wondering where things stand now. Activity on this project seems pretty slow. Is that because it's mature and does what people need? Or is it moribund? Have people moved on to other solutions?

I love how easy it is to use, but I'm running into performance problems.

Thanks!

**Comment by hooch** [comment]
bump
