### ISSUE TITLE
Need more examples, thanks!

### ISSUE THREAD

**Issue by ssr66994053** [elgerlambert/redux-localstorage#53]
sorry, i am new to this. after read the doc(v1.0), i am still don't know how use it in my project. could you please give me some more examples?

"dependencies": {
    "material-ui": "^0.15.3",
    "radium": "^0.18.1",
    "react": "^15.2.0",
    "react-dom": "^15.2.0",
    "react-redux": "^4.4.5",
    "react-router": "^2.5.2",
    "react-router-redux": "^4.0.5",
    "react-tap-event-plugin": "^1.0.0",
    "redux": "^3.5.2",
    "redux-localstorage": "^1.0.0-rc5",
    "redux-localstorage-filter": "^0.1.1",
    "redux-logger": "^2.6.1",
    "redux-saga": "^0.10.5"
  }

**Comment by ssr66994053** [comment]
i got it! the key in `filter` must be the state map to props. like below:

``` js
const storage = compose(
  filter('counter')
)(adapter(window.localStorage));

....

const mapStateToProps = (state) => ({
  counter: state.counter,
})

const enhancers = compose(
  /* middlewares */
  persistState(storage, 'my-storage-key')
)
```

then in the local storage will have this

``` json
my-storage-key : {"counter": 0}
```

**Comment by ghost** [comment]
Hello, Have you ever encountered this problem?
```
 const logger = createLogger({ stateTransformer });
    const middlewares = [
        thunkMiddleware,
        sagaMiddleware,
        logger,
        routerMiddleware(createHistory()),
    ];

    const reducer = compose(
        mergePersistedState()
    )(createReducer);

    const storage = compose(
        filter('app')
    )(adapter(window.localStorage));

    const enhancer = compose(
        applyMiddleware(...middlewares),
        persistState(storage),
        devtools,
    );
```

![8o9 ozdg bou txfx yg](https://cloud.githubusercontent.com/assets/16831715/24130700/2cc1808e-0e25-11e7-8ffa-9774b9de1b4f.png)

```
    "immutable": "^3.8.1",
    "react": "^15.2.1",
    "react-dom": "^15.2.1",
    "react-redux": "^4.4.5",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.6",
    "redux": "^3.5.2",
    "redux-actions": "^0.12.0",
    "redux-immutable": "^3.0.8",
    "redux-logger": "^2.6.1",
    "redux-saga": "^0.12.0",
    "redux-thunk": "^2.1.0",
    "reselect": "^2.5.4",
```
