### ISSUE TITLE
Setup for config in persistState

### ISSUE THREAD

**Issue by Petesta** [elgerlambert/redux-localstorage#55]
Hi, I'm struggling to figure out how to select a subset of what `config` needs to look like with keys/values inside of `persistState`.  There are code snippets but it's a little difficult to piece them together and figure out what is needed to just select a subset of fields to sync to `localStorage`. Would you be able to elaborate more on how to accomplish this? My state currently looks like below.

``` javascript
{
  key1: {},
  key2: {
    innerKey1: [],
    innerKey2: [],
    innerKey3: null
  }
}
```

If I wanted to select `innerKey1` here, how would I go about that?

``` javascript
// Pseudocode
compose(
  applyMiddleware(thunk),
  persistState('key2', /* config_to_access_innerKey1 */)
);
```

**Comment by Petesta** [comment]
In the `README.md` there is a code snippet for creating a customer slicer. However, I think the code is wrong since in the source when you refer to your `slicer` with `var slicerFn = slicer(paths)`
the code below...

``` javascript
function myCustomSlicer (paths) {
  return (state) => {
    let subset = {}
    /*Custom logic goes here*/
    return subset
  }
}
```

Returns an object, not a function which is expected.

<img width="575" alt="screen shot 2016-09-14 at 10 57 53 am" src="https://cloud.githubusercontent.com/assets/1114813/18523917/24b54bee-7a6b-11e6-9d1c-39b3092eaf5a.png">

It seems like the code should be something of this sort.

``` javascript
function myCustomSlicer (paths) {
  return (state) => {
    let subset = {}
    /*Custom logic goes here*/
    return () => { subset }
  }
}
```

Also, `state` in these functions always happens to be a `String` and not sure why. Shouldn't it be an object?

**Comment by lbalceda** [comment]
@elgerlambert could you give an example of how to include only certain inner keys ?

**Comment by Petesta** [comment]
Here's how it needs to be done.

``` javascript
function customSlicer() {
  return (state) => {
    const { auth } = state;
    return { auth };
  }
}

compose(
  applyMiddleware(thunk),
  persistState(null, { slicer: myCustomSlicer() })
);
```

**Comment by lbalceda** [comment]
cool, thanks!

**Comment by cyberpolin** [comment]
Any one is getting 
```TypeError: Object(...) is not a function```
