### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by vincaslt** [elgerlambert/redux-localstorage#71]
Definitions installed from @types/redux-localstorage seem to be either old or incorrect. I can't make sense of them:

```
export default function persistState<A>(storage?: StorageAdapter<A>, key?: string, callback?: Function): Redux.GenericStoreEnhancer;
```

This doesn't look like the function in doc examples.

**Comment by calvin** [comment]
Use `redux-localstorage@rc`.
