### ISSUE TITLE
.bablerc file preventing compilation with Babel 6

### ISSUE THREAD

**Issue by EmmaSimon** [elgerlambert/redux-localstorage#72]
I'm using Babel 6.24, and after installing this package, it throws:
```
ERROR in ./~/redux-localstorage/lib/persistState.js
Module build failed: ReferenceError:
[BABEL] /home/emma/.../node_modules/redux-localstorage/lib/persistState.js:
Using removed Babel 5 option: /home/emma/.../node_modules/redux-localstorage/.babelrc.stage -
Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
```
After removing `node_modules/redux-localstorage/.babelrc`, everything works fine.

**Comment by yanghealsci** [comment]
+1
Have the same problem, but ONLY on windows. It works well for linux and mac, no error were thrown.

**Comment by EmmaSimon** [comment]
@yanghealsci Hm, I'm having the issue on Linux (Debian 9).

**Comment by lewisbarber** [comment]
Yep I just had this problem too. Deleting .babelrc fixes it...

**Comment by DiesIrae** [comment]
Same issue on mac... :-(

**Comment by alexanderwallin** [comment]
@EmmaSimon You should generally not transpile anything inside the `node_modules` directory. Are you using Webpack? A common mistake is to omit `ignore: [/node_modules/]` from the `babel-loader` configuration.

**Comment by EmmaSimon** [comment]
@alexanderwallin Ah, yep, I'm doing that now, though I wasn't when I wrote this. 😛
