### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rekmarks** [elgerlambert/redux-localstorage#93]
Hey @elgerlambert,

Are you still maintaining the redux-localstorage packages?

If so, are you entertaining PRs?

Best,
Erik Marks

**Comment by ptytb** [comment]
It seems that new apps should use [redux-persist](https://github.com/rt2zz/redux-persist), as it supports a motley crew of storage engines including Local Storage

**Comment by rekmarks** [comment]
@ptytb Good catch, I'll just move to that instead. Thanks!
